# Generated by Django 3.0.5 on 2020-05-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_img_imglabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imglabel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
