# Generated by Django 3.0.5 on 2020-05-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0005_auto_20200503_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='label',
            new_name='label_id',
        ),
        migrations.RenameField(
            model_name='imglabel',
            old_name='label',
            new_name='label_id',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='category',
            new_name='model_category_id',
        ),
    ]
