# Generated by Django 3.0.5 on 2020-05-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0006_auto_20200503_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='model_category_id',
            new_name='category_id',
        ),
    ]
