# Generated by Django 3.0.5 on 2020-05-03 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0008_auto_20200503_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imglabel',
            options={'verbose_name': '图片标签', 'verbose_name_plural': '图片标签'},
        ),
        migrations.AlterModelTable(
            name='imglabel',
            table='img_table',
        ),
    ]
