# Generated by Django 3.0.5 on 2020-05-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0010_auto_20200503_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='input_shape',
            field=models.CharField(default='1,1,1', max_length=255),
        ),
        migrations.AddField(
            model_name='model',
            name='summary',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
