# Generated by Django 3.0.5 on 2020-05-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0011_auto_20200505_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='input_shape',
        ),
        migrations.RemoveField(
            model_name='model',
            name='summary',
        ),
        migrations.AddField(
            model_name='modelcategory',
            name='input_shape',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='modelcategory',
            name='summary',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
