# Generated by Django 3.0.5 on 2020-05-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0012_auto_20200505_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
