# Generated by Django 3.0.5 on 2020-05-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0014_model_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='acc',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='model',
            name='batch_size',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='model',
            name='epoch',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='model',
            name='test_x',
            field=models.IntegerField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='model',
            name='train_x',
            field=models.IntegerField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='model',
            name='y',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='model',
            name='size',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
