# Generated by Django 3.0.5 on 2020-05-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0016_auto_20200507_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='model',
            name='input_shape',
            field=models.CharField(default='', max_length=30),
        ),
    ]
