# Generated by Django 3.0.6 on 2020-05-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0017_auto_20200507_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='size',
            field=models.CharField(default='', max_length=50),
        ),
    ]
